# Generated by Django 5.1.7 on 2025-03-24 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Nombre del estado')),
                ('description', models.TextField(blank=True, help_text='Campo opcional', null=True, verbose_name='Descripción')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug del estado')),
            ],
            options={
                'verbose_name': 'Estado del cliente',
                'verbose_name_plural': 'Estados de los clientes',
                'db_table': 'clients_status',
            },
        ),
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Campo obligatorio', max_length=150, unique=True, verbose_name='Nombre de compañia')),
                ('contact_name', models.CharField(help_text='Campo obligatorio', max_length=100, verbose_name='Persona de contacto')),
                ('email', models.EmailField(help_text='Campo obligatorio', max_length=254, unique=True, verbose_name='Correo de contacto')),
                ('phone', models.CharField(blank=True, help_text='Campo opcional', null=True, verbose_name='Teléfono de contacto')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug del cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('status', models.ForeignKey(blank=True, help_text='Campo opcional', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='clients', to='clients.clientstatusmodel', verbose_name='Estado del cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clients',
            },
        ),
    ]
