# Generated by Django 5.1.7 on 2025-03-25 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField(help_text='Campo obligatorio - máximo 150 caractéres', max_length=150, verbose_name='Proposito de reunión')),
                ('date', models.DateTimeField(verbose_name='Fecha de reunión')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
            ],
            options={
                'verbose_name': 'Reunión',
                'verbose_name_plural': 'Reuniones',
                'db_table': 'meetings',
            },
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='meetings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='clients', to='clients.meetingmodel', verbose_name='Reuniones'),
        ),
    ]
